stderr of test 'ID.1210173-0` in directory 'tests/BugsViaSourgeforce` itself:


# 01:35:02 >  
# 01:35:02 >  Mtimeout -timeout 60 Mserver "--config=/var/tmp/_Stable_PREFIX__GNU_32_d_--enable-debug_/etc/MonetDB.conf" --debug=10 --set "monet_mod_path=/var/tmp/_Stable_PREFIX__GNU_32_d_--enable-debug_/lib/MonetDB:/var/tmp/_Stable_PREFIX__GNU_32_d_--enable-debug_/lib/bin" --set "gdk_dbfarm=/var/tmp/_Stable_PREFIX__GNU_32_d_--enable-debug_/var/MonetDB/dbfarm" --set "sql_logdir=/var/tmp/_Stable_PREFIX__GNU_32_d_--enable-debug_/var/MonetDB/log" --set mapi_port=37317 --set sql_port=40365 --set xquery_port=52374 --set monet_prompt= --trace --dbname=mTests_tests_BugsViaSourgeforce  < ID.1210173-0.milS
# 01:35:02 >  


# 01:35:03 >  
# 01:35:03 >  Done.
# 01:35:03 >  

