stderr of test 'ID.1010729` in directory 'monetdb5/tests/BugsViaSourgeforce` itself:


# 23:29:44 >  
# 23:29:44 >  Mtimeout -timeout 60 Mserver "--config=/var/tmp/_PREFIX__GNU_32_d__/etc/monet.conf" --debug=10 --set "monet_mod_path=/var/tmp/_PREFIX__GNU_32_d__/lib/MonetDB" --set "gdk_dbfarm=/var/tmp/_PREFIX__GNU_32_d__/var/MonetDB/dbfarm" --set "sql_logdir=/var/tmp/_PREFIX__GNU_32_d__/var/MonetDB/log" --set mapi_port=41908 --set sql_port=57358 --set monet_prompt= --trace --dbname=mTests_tests_BugsViaSourgeforce  < ID.1010729.milS
# 23:29:44 >  


# 23:29:45 >  
# 23:29:45 >  Done.
# 23:29:45 >  

