stderr of test 'ID.823516` in directory 'monetdb5/tests/BugsViaSourgeforce` itself:


# 17:19:55 >  
# 17:19:55 >  Mtimeout -timeout 60 Mserver "--config=/var/tmp/_PREFIX_MONET_GNU_32_d__/etc/monet.conf" --debug=10 --set "monet_mod_path=/var/tmp/_PREFIX_MONET_GNU_32_d__/lib/MonetDB" --set "gdk_dbfarm=/var/tmp/_PREFIX_MONET_GNU_32_d__/var/MonetDB/dbfarm" --set "sql_logdir=/var/tmp/_PREFIX_MONET_GNU_32_d__/var/MonetDB/log" --set mapi_port=53383 --set sql_port=50018 --set monet_prompt= --trace --dbname=mTests_tests_BugsViaSourgeforce  < ID.823516.milM
# 17:19:55 >  


# 17:19:56 >  
# 17:19:56 >  Done.
# 17:19:56 >  

