stderr of test 'ID.991053` in directory 'monetdb5/tests/BugsViaSourgeforce` itself:


# 20:22:17 >  
# 20:22:17 >  Mtimeout -timeout 60 Mserver "--config=/var/tmp/_PREFIX__GNU_32_d_--enable-debug_/etc/monet.conf" --debug=10 --set "monet_mod_path=/var/tmp/_PREFIX__GNU_32_d_--enable-debug_/lib/MonetDB" --set "gdk_dbfarm=/var/tmp/_PREFIX__GNU_32_d_--enable-debug_/var/MonetDB/dbfarm" --set "sql_logdir=/var/tmp/_PREFIX__GNU_32_d_--enable-debug_/var/MonetDB/log" --set mapi_port=42145 --set sql_port=55242 --set monet_prompt= --trace --dbname=mTests_tests_BugsViaSourgeforce  < ID.991053.milS
# 20:22:17 >  



# 20:26:10 >  
# 20:26:10 >  Done.
# 20:26:10 >  

