stdout of test 'tst300` in directory 'src/mal` itself:


# 08:01:13 >  
# 08:01:13 >  Mtimeout -timeout 60 Mserver "--config=/ufs/mk/monet5/Linux/etc/MonetDB5.conf" --debug=10 --set "monet_mod_path=/ufs/mk/monet5/Linux/lib/MonetDB5:/ufs/mk/opensource/MonetDB/Linux/lib/MonetDB" --set "gdk_dbfarm=/ufs/mk/monet5/Linux/var/MonetDB5/dbfarm" --set "sql_logdir=/ufs/mk/monet5/Linux/var/MonetDB5/log" --set mapi_port=42158 --set sql_port=55708 --set monet_prompt= --trace "--config=/ufs/mk/monet5/src/mal/Tests/All.conf" --dbname=mTests_src_mal  tst300.mal </dev/null
# 08:01:13 >  

# Monet Database Server V4.99.19
# Copyright (c) 1993-2004, CWI. All rights reserved.
# Compiled for i686-redhat-linux-gnu/32bit; dynamically linked.
# config:/ufs/mk/monet5/Linux/etc/MonetDB5.conf
# dbfarm:/ufs/mk/monet5/Linux/var/MonetDB5/dbfarm
# dbname:mTests_src_mal
# Visit http://monetdb.cwi.nl/ for further information.
## Exception identifiers can be introduced at any place
#
#	raise myNewException:= "new exception";
#	printf("should not come here\n");
##exception block;
#catch	myNewException;
#	printf("catched exception\n");
#exit	myNewException;
#end tst;
function user.tst():void;               #  0 tst:void := user.tst() {G}
    raise myNewException:str  := "new exception";#  1 myNewException:str := _2:str {G}
    io.printf("should not come here\n");#  2 _3:void := IOprint_str(_4:str) 
#exception block; 
catch myNewException:str ;              #  4 myNewException:str {J6}
    io.printf("catched exception\n");   #  5 _6:void := IOprint_str(_7:str) 
exit myNewException:str ;               #  6 myNewException:str 
end tst;	# 7  
#
#tst();
#
function user.main():void;              #  0 main:void := user.main() 
# Exception identifiers can be introduced at any place 
    user.tst();                         #  2 _2:void := user.tst() 
end main;	# 3  
catched exception

# 08:01:13 >  
# 08:01:13 >  Done.
# 08:01:13 >  

