stdout of test 'tst305` in directory 'src/mal` itself:


# 08:01:17 >  
# 08:01:17 >  Mtimeout -timeout 60 Mserver "--config=/ufs/mk/monet5/Linux/etc/MonetDB5.conf" --debug=10 --set "monet_mod_path=/ufs/mk/monet5/Linux/lib/MonetDB5:/ufs/mk/opensource/MonetDB/Linux/lib/MonetDB" --set "gdk_dbfarm=/ufs/mk/monet5/Linux/var/MonetDB5/dbfarm" --set "sql_logdir=/ufs/mk/monet5/Linux/var/MonetDB5/log" --set mapi_port=42158 --set sql_port=55708 --set monet_prompt= --trace "--config=/ufs/mk/monet5/src/mal/Tests/All.conf" --dbname=mTests_src_mal  tst305.mal </dev/null
# 08:01:17 >  

# Monet Database Server V4.99.19
# Copyright (c) 1993-2004, CWI. All rights reserved.
# Compiled for i686-redhat-linux-gnu/32bit; dynamically linked.
# config:/ufs/mk/monet5/Linux/etc/MonetDB5.conf
# dbfarm:/ufs/mk/monet5/Linux/var/MonetDB5/dbfarm
# dbname:mTests_src_mal
# Visit http://monetdb.cwi.nl/ for further information.
#
## Exceptions can be explicitly raised in a function
## which requires the exception identifier to be defined.
#
#function myException();
#raise	IllegalAccess:="new exception";
#	print("should have left function ");
#end myException;
function user.myException():void;       #  0 myException:void {G}
    raise IllegalAccess := "new exception";#  1 IllegalAccess:str := _2:str {G}
    io.print("should have left function ");#  2 _3:void := IOprint_val(_4:str) 
end myException;	# 3  
#
#	myException();
#	print("should not come here");
#
function user.main():void;              #  0 main:void 
# Exceptions can be explicitly raised in a function 
# which requires the exception identifier to be defined. 
    user.myException();                 #  3 _3:void 
    io.print("should not come here");   #  4 _4:void := IOprint_val(_5:str) 
end main;	# 5  
!MALException:user.myException[1]:new exception
!MALException:user.myException[3]:Exception not catched

# 17:45:30 >  
# 17:45:30 >  Done.
# 17:45:30 >  

