stderr of test 'document_handling.SF-1618802.unpack_docs` in directory 'tests/BugTracker` itself:


# 15:46:16 >  
# 15:46:16 >  Mtimeout -timeout 60 /usr/bin/python document_handling.SF-1618802.unpack_docs.py document_handling.SF-1618802.unpack_docs 
# 15:46:16 >  


# 15:46:16 >  
# 15:46:16 >  unzip document_handling.SF-1618802.unpack_docs.zip
# 15:46:16 >  


# 15:46:16 >  
# 15:46:16 >  Done.
# 15:46:16 >  

