stderr of test 'file_locked_after_shredding.SF-1238352` in directory 'tests/BugDay_2005-12-19_0.9.3` itself:


# 22:08:32 >  
# 22:08:32 >  Mtimeout -timeout 240 Mserver "--config=/ufs/niels/scratch/rc/Linux-x86_64/etc/MonetDB.conf" --debug=10 --set "monet_mod_path=/ufs/niels/scratch/rc/Linux-x86_64/lib64/MonetDB:/ufs/niels/scratch/rc/Linux-x86_64/lib64/MonetDB/lib:/ufs/niels/scratch/rc/Linux-x86_64/lib64/MonetDB/bin" --set "gdk_dbfarm=/ufs/niels/scratch/rc/Linux-x86_64/var/MonetDB/dbfarm" --set "sql_logdir=/ufs/niels/scratch/rc/Linux-x86_64/var/MonetDB/sql_logs" --set "sql_logdir=/ufs/niels/scratch/rc/Linux-x86_64/var/MonetDB/xquery_logs" --set mapi_port=31763 --set monet_prompt= --trace "--dbname=mTests_tests_BugDay_2005-12-19_0.9.3" --dbinit=" module(pathfinder); module(mapi); mil_start(); module(mapi); mil_start();" ; echo ; echo Over..
# 22:08:32 >  


# 12:43:36 >  
# 12:43:36 >  Mtimeout -timeout 60 python file_locked_after_shredding.SF-1238352.MAPI.py file_locked_after_shredding.SF-1238352 
# 12:43:36 >  


# 12:45:19 >  
# 12:45:19 >  Done.
# 12:45:19 >  

