stderr of test 'ID.1032186` in directory 'tests/BugsViaSourgeforce` itself:


# 23:41:28 >  
# 23:41:28 >  Mtimeout -timeout 60 Mserver "--config=/var/tmp/_4.4.0_PREFIX_MONETDB_GNU_32_d__/etc/MonetDB.conf" --debug=10 --set "monet_mod_path=/var/tmp/_4.4.0_PREFIX_MONETDB_GNU_32_d__/lib/MonetDB" --set "gdk_dbfarm=/var/tmp/_4.4.0_PREFIX_MONETDB_GNU_32_d__/var/MonetDB/dbfarm" --set "sql_logdir=/var/tmp/_4.4.0_PREFIX_MONETDB_GNU_32_d__/var/MonetDB/log" --set mapi_port=40941 --set sql_port=53532 --set monet_prompt= --trace --dbname=mTests_tests_BugsViaSourgeforce  < ID.1032186.milS
# 23:41:28 >  


# 23:41:30 >  
# 23:41:30 >  Done.
# 23:41:30 >  

