stderr of test 'currenttime.Bug-2791` in directory 'test/BugTracker-2012` itself:


# 13:47:05 >  
# 13:47:05 >  "/usr/bin/python" "currenttime.Bug-2791.py" "currenttime.Bug-2791"
# 13:47:05 >  

#mserver
#client
# builtin opt 	gdk_dbname = demo
# builtin opt 	gdk_dbfarm = /export/scratch2/duc/work/BugsDay/MonetDB/var/monetdb5/dbfarm
# builtin opt 	gdk_debug = 0
# builtin opt 	gdk_vmtrim = yes
# builtin opt 	monet_prompt = >
# builtin opt 	monet_daemon = no
# builtin opt 	mapi_port = 50000
# builtin opt 	mapi_open = false
# builtin opt 	mapi_autosense = false
# builtin opt 	sql_optimizer = default_pipe
# builtin opt 	sql_debug = 0
# cmdline opt 	gdk_nr_threads = 0
# cmdline opt 	gdk_dbfarm = /export/scratch2/duc/work/BugsDay/MonetDB/var/MonetDB
# cmdline opt 	mapi_open = true
# cmdline opt 	mapi_port = 30109
# cmdline opt 	monet_prompt = 
# cmdline opt 	mal_listing = 2
# cmdline opt 	gdk_dbname = mTests_test_BugTracker-2012


