# This tests the saveguards for highly recursive programs.
# The first p() invocation will give a physical out of stack error.  
# The others together generate a physical out-of-context error.
# This, however, is rather undeterministic and depends
# on the parallelism achieved.
# What it *should* do is not crash, and print the [42]

module(alarm);
proc p;
proc p(int i) : void { if (i < 10000) p(i+1); }
{
p(100).fork();
p(300).fork();
p(301).fork();
p(302).fork();
p(303).fork();
p(304).fork();
sleep(10);
}
print(42);

quit();
