stderr of test 'good-009` in directory 'tests/i18n` itself:


# 09:36:59 >  
# 09:36:59 >  Mtimeout -timeout 180 Mserver "--config=/opt/MonetDB/etc/MonetDB.conf" --debug=10 --set "monet_mod_path=/home/teubner/pf/cvs-head/runtime/.libs:/home/teubner/pf/cvs-head/runtime:/opt/MonetDB/lib/MonetDB" --set "gdk_dbfarm=/home/teubner/pf/cvs-head/dbfarm" --set "sql_logdir=/home/teubner/pf/cvs-head/log" --set mapi_port=39068 --set monet_prompt= --trace "--dbname=mTests_tests_i18n" --dbinit="module(pathfinder); pfstart();" ; echo ; echo Over..
# 09:36:59 >  


# 09:37:00 >  
# 09:37:00 >  Mtimeout -timeout 60 MapiClient -lxquery -oxml -umonetdb -Pmonetdb --host=localhost --port=39068 good-009.xq
# 09:37:00 >  


# 09:37:00 >  
# 09:37:00 >  Done.
# 09:37:00 >  

