stderr of test 'good-002` in directory 'tests/i18n` itself:


# 22:24:16 >  
# 22:24:16 >  Mtimeout -timeout 180 Mserver "--config=/opt/MonetDB/etc/MonetDB.conf" --debug=10 --set "monet_mod_path=/home/teubner/pf/cvs-head/runtime/.libs:/home/teubner/pf/cvs-head/runtime:/opt/MonetDB/lib/MonetDB" --set "gdk_dbfarm=/home/teubner/pf/cvs-head/dbfarm" --set "sql_logdir=/home/teubner/pf/cvs-head/log" --set mapi_port=30263 --set monet_prompt= --trace "--dbname=mTests_tests_i18n" --dbinit="module(pathfinder); pfstart();" ; echo ; echo Over..
# 22:24:16 >  


# 22:24:17 >  
# 22:24:17 >  Mtimeout -timeout 60 MapiClient -lxquery -fxml -umonetdb -Pmonetdb --host=localhost --port=30263 good-002.xq
# 22:24:17 >  


# 22:24:17 >  
# 22:24:17 >  Done.
# 22:24:17 >  

